### ISSUE TITLE
Not working on my site, can you give me a hand for a sec?

### ISSUE THREAD

**Issue by pierreremybalian** [rewdy/leaveNotice#3]
Hello, I'm not very well versed in Javascript, but I thought I had this installed properly but it is not working. 

The site is salt101.com

Here is the code I tried using...

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>

<script type="text/javascript" language="javascript" src="http://www.salt101.com/templates/protostar/js/jquery.leaveNotice.min.js"></script>

<script type="text/javascript" language="javascript"> 
    $(function(){
    $('a[rel=external]').leaveNotice({
        siteName: 'Salt101'
    });
    });
</script>

Any help or pointers would be much appreciated!

**Comment by pierreremybalian** [comment]
BTW I am not calling the css file because I just dumped all the code in my main template css file.

**Comment by rewdy** [comment]
Yeah, I can help.

The code you are using to initiate leaveNotice looks for links with the attribute `rel="external"`. This is suggested because it's somewhat more standards-compliant, however, it's not often the most convenient way to do it. In order to make that code work, you'd have to put `rel="external"` on all your external links. (Not probably something you want to do.)

I took a look at your site and it seems that you internal sites links are all relative (i.e. they links to "/something" as opposed to "http://www.salt101.com/whatever".) Since this is the case, you can initiate the plug in so it applies the behavior to all links that start with "http://", thus targeting the external links. Here's how you would do it:

``` javascript
$(function(){
    $('a[href^="http"]').leaveNotice({siteName: 'Salt101'});
});
```

Let me know if that works for you. Good luck! :)

**Comment by pierreremybalian** [comment]
Hi, thanks for taking the time to give me a hand.  
Unfortunately your code isnt working for me, also I even tried adding rel="external" to my link as well and that isn't working either. 

Right now I put the script right before the end of <head> in my CMS templates index file with all my other scripts. Is this the best place for this?    I'm sure your script works fine I am just screwing this up somehow.

**Comment by rewdy** [comment]
I'm not totally sure. Right now, it appears you have two closing `});`s that is throwing an error. You can remove one of those. 

Other things to try:

You can omit including the jQuery library before you include the leaveNotice script. This is because I can see that your site is already calling in jQuery. There's no need to call it in twice. That could help.

The other thing is that since you're also using Mootools (at least the script is being called in), you can try replacing the dollar sign with 'jQuery'. Sometimes that creates problems.

So, you'd have:

``` javascript
jQuery(function(){
    jQuery(...same as before...);
});
```

See if that gets your anywhere...

**Comment by rewdy** [comment]
I'm closing this ticket from lack of activity. If you continue to have trouble, you can let me know andrew [at] rewdy [dot] com
